In [1]:
import pandas as pd
import numpy as np
import re
import os
import matplotlib as mpl
import json

from collections import Counter

import warnings
warnings.filterwarnings('ignore')

In [2]:
def count_list_of_list(list_of_lists):
    """
    Input: List of list of keywords
    Output: {keyword: count} dict
    """
    counter = Counter()

    # Allowed characters: letters, digits, spaces, and selected punctuation
    allowed_pattern = r"[a-z0-9\s\-/.,&'():]+"

    for sublist in list_of_lists:
        cleaned_items = set()
        for word in sublist:
            if not isinstance(word, str):
                continue
            w = word.strip().lower()

            if re.fullmatch(allowed_pattern, w):
                cleaned_items.add(w)

        counter.update(cleaned_items)

    return dict(counter)

def count_list(words):

    cleaned = [
        w.lower()
        for w in words
        if isinstance(w, str) and len(w.strip()) >= 1
    ]
    
    # Count the terms
    return dict(Counter(cleaned))

def count_unique_keywords(keywords):
    if not keywords:
        return {}

    # Case 1: List[str]
    if isinstance(keywords[0], str):
        return count_list(keywords)

    # Case 2: List[List[str]]
    if isinstance(keywords[0], (list, np.ndarray)):
        return count_list_of_list(keywords)

    # Otherwise raise error
    raise TypeError(
        f"Invalid keywords type: expected List[str] or List[List[str]], "
        f"got element of type {type(keywords[0])}"
    )


def counter_to_df(word_counts, store_name):
    df = pd.DataFrame(word_counts.items(), columns=['keyword', 'count'])
    df = df.sort_values(by='count', ascending=False, ignore_index=True)
    df['store_name'] = store_name
    return df

def item_list_to_df(store_keywords, store_name):
    word_count_dict = count_unique_keywords(store_keywords)
    res = counter_to_df(word_count_dict, store_name)
    return res
    
def join_keywords_in_list(list_of_lists, special_color="green", max_words=3):
    result = []
    for colors in list_of_lists:
        # Always include special_color if present
        has_special = special_color in colors

        # Take first max_words items, but ensure special_color is kept
        subset = colors[:max_words]
        if has_special and special_color not in subset:
            # Replace last element with special_color (preserve max length)
            if len(subset) == max_words:
                subset[-1] = special_color
            else:
                subset.append(special_color)

        # ✅ Only ensure special_color comes first, preserve original order otherwise
        subset = list(subset)
        subset.sort(key=lambda c: (c != special_color, c))

        # Join and wrap in list
        result.append([" ".join(subset)])
    return result


""" Add param to allow for combining of keywords """
def keyword_count_store_key_df(df, key, store_name, join_keywords = False):
    # Get [['cypress', 'fir'], ['magnolia']] 
    store_df = df[df.store_name == store_name]
    store_keywords =  store_df[key].values.tolist()

    # if flatten: store_keywords = ...
    if join_keywords:
        store_keywords = join_keywords_in_list(store_keywords)

    res = item_list_to_df(store_keywords, store_name)
    return res

In [3]:
def minmax_scale(data):
    """
    Scales a list or numpy array of numbers to the range [0, 100].
    Handles edge cases like constant values safely.
    """
    arr = np.array(data, dtype=float)
    min_val, max_val = np.min(arr), np.max(arr)

    # Avoid division by zero if all values are equal
    if min_val == max_val:
        return np.zeros_like(arr)

    scaled = (arr - min_val) / (max_val - min_val) * 100
    return scaled

def pivot_keyword_dfs(dfs: list[pd.DataFrame]) -> pd.DataFrame:
        
    if not dfs:
        return pd.DataFrame()

    # Combine all DataFrames
    merged_df = pd.concat(dfs, ignore_index=True)

    # Pivot table: keywords as rows, store_names as columns
    pivot_df = merged_df.pivot_table(
        index='keyword',
        columns='store_name',
        values='count',
        aggfunc='sum',  # if duplicates exist, sum counts
        fill_value=0
    )
    
    return pivot_df

def get_pct_stores(df: pd.DataFrame) -> pd.DataFrame:
    """
    Adds a 'pct_stores' column showing the fraction of stores
    (columns) where the keyword has a count > 0. 
    Then sorts by pct_stores descending, then by row sum of counts descending.
    """
    pivot_df = df.copy()
    store_count = pivot_df.shape[1]
    
    # Compute pct_stores
    pivot_df['pct_stores'] = (pivot_df.gt(0).sum(axis=1) / store_count).round(2)
    
    # Compute row sum across numeric columns excluding pct_stores
    numeric_cols = pivot_df.select_dtypes(include='number').columns.tolist()
    sum_cols = [col for col in numeric_cols if col != 'pct_stores']
    
    item_totals = pivot_df[sum_cols].sum(axis=1).values
    pivot_df['score'] = minmax_scale(item_totals)/100
    
    # Sort first by pct_stores, then by row sum
    pivot_df = pivot_df.sort_values(by=['score', 'pct_stores'], ascending=False)
    pivot_df = pivot_df[[c for c in pivot_df.columns if c != 'pct_stores'] + ['pct_stores']]
    
    return pivot_df

In [4]:
def divide_df_by_store_sizes(df, store_sizes):
    print(df.columns)
    if len(df.columns) != len(store_sizes):
        raise ValueError("❌ Length of store_sizes must match number of DataFrame columns.")
    
    # Convert to Series for broadcasting
    divisors = pd.Series(store_sizes, index=df.columns)
    return df.divide(divisors, axis='columns')

def normalize_store_columns(df: pd.DataFrame) -> pd.DataFrame:
    # Exclude non-numeric columns like 'pct_stores' if present
    numeric_df = df.select_dtypes(include='number')

    # Compute column-wise percentages
    pct_df = numeric_df.div(numeric_df.sum(axis=0), axis=1).round(2)

    # Retain non-numeric columns if any
    non_numeric = df.drop(columns=numeric_df.columns, errors='ignore')
    result = pd.concat([pct_df, non_numeric], axis=1)

    return result

def normalize_pivot_df(df, store_sizes, how = "store_size"):
    # print(df)
    if how == "store_size":
        return divide_df_by_store_sizes(df, store_sizes)
    else:
        return normalize_store_columns(df)

def generate_pivots(dfs, store_sizes, store_names = None, how = "store_size"):
    pivot_df = pivot_keyword_dfs(dfs)
    pivot_df = pivot_df[store_names]

    # EITHER BY STORE SIZE OF NORMALIZE
    pivot_df_pcts = normalize_pivot_df(pivot_df, store_sizes, how = how)

    pivot_df = pivot_df[store_names]
    pivot_df_pcts = pivot_df_pcts[store_names]
    
    return pivot_df, pivot_df_pcts

def aggregate_count_dfs(dfs, store_sizes, store_names = None, how = "store_size"):
    pivot_df, pivot_df_pcts = generate_pivots(dfs, store_sizes, store_names, how)
    # print(pivot_df)
    # MAKE SURE STORE COLUMNS MATCH

    count_df = get_pct_stores(pivot_df)
    pct_df = get_pct_stores(pivot_df_pcts)

    count_df = count_df[count_df.pct_stores > 0]
    pct_df = pct_df[pct_df.pct_stores > 0]

    return count_df, pct_df

def colorize_df(df: pd.DataFrame, base_cmap: str = "Greens", min_frac: float = 0.0, max_frac: float = 0.6):
    # Get original colormap
    cmap_orig = mpl.cm.get_cmap(base_cmap)
    
    # Slice colormap to soften extremes
    cmap_vals = cmap_orig(np.linspace(min_frac, max_frac, 256))
    # Remove alpha channel for pandas
    cmap_vals = cmap_vals[:, :-1]
    soft_cmap = mpl.colors.ListedColormap(cmap_vals)

    return (
        df.style
        .background_gradient(cmap=soft_cmap, vmin=0, vmax=100, axis=None)
        .format("{:.0f}%")
    )

def generate_color_map(dfs, store_sizes, store_names, how = "store_size"):
    count_pivot, pct_pivot = aggregate_count_dfs(dfs, store_sizes, store_names, how)
    return count_pivot, pct_pivot, colorize_df(pct_pivot*100)

In [5]:
def df_to_colortable(df, key, how = 'store_size', join_keywords = False):
    # Get df of keyword counts for each store
    store_names = df.store_name.unique()
    keyword_count_dfs = [keyword_count_store_key_df(df, key, store, join_keywords) for store in store_names]
    store_sizes = [len(df[df.store_name == store]) for store in store_names]
    print("store_sizes", store_sizes)

    # Pivot
    counts, pcts, color_table = generate_color_map(keyword_count_dfs, store_sizes, store_names, how)
    return counts, pcts, color_table

### Try!

##### Load df

In [6]:
df = pd.read_parquet("final_flower_america_df.parquet")

In [14]:
df[df['flower_type'].apply(lambda x: len(x) > 1)]

,Name,Description,Price,store_name,Store Type,Store Quality,Product Type,Product Link,Main Img Link,filename,plant_type,flower_type,flower_colors,leaf_type,product_type,container,how_many_flowers,name_normalized,flowers_in_name
83,Faux-Ever Large Cream White Fake Rose and Peon...,Make your wedding day stress-free when you cho...,$120.00,Aflora,Independent Website,A,All Artificial Flowers,https://www.afloral.com/collections/artificial...,https://www.afloral.com/cdn/shop/files/PDP_58_...,Image_84,flower,"[peony, rose]",[white],[],single stem,none,2,faux-ever large cream white fake rose and peon...,"[peony, rose]"
179,Pink Cream Fake Peony and Eucalyptus Flower Bo...,Embrace the versatility of premade artificial ...,$36.00,Aflora,Independent Website,A,All Artificial Flowers,https://www.afloral.com/collections/artificial...,https://www.afloral.com/cdn/shop/files/Afloral...,Image_180,flower,"[peony, hydrangea]","[pink, red, white]",[eucalyptus],single stem,none,2,pink cream fake peony and eucalyptus flower bo...,"[eucalyptus, peony]"
347,Coral Garden Arrangement,Elevate your home dcor with vibrant blooms. Sh...,$299,Balsam Hill,Independent Website,A,Spring Artificial Flowers & Floral Dcor,https://www.balsamhill.com/f/coral-garden-flor...,https://source.widen.net/content/zumk7pwyqz/we...,Image_3,flower,"[peony, dahlia, hydrangea, ranunculus]","[green, orange, peach]",[],arrangement,vase,4,coral garden arrangement,[]
348,Southern Charm Arrangement,Bring warmth and elegance to your home with th...,$299,Balsam Hill,Independent Website,A,Spring Artificial Flowers & Floral Dcor,https://www.balsamhill.com/f/southern-charm-fl...,https://source.widen.net/content/4uvhazrjlf/we...,Image_4,flower,"[rose, hydrangea]",[white],[],arrangement,pot,2,southern charm arrangement,[]
349,Outdoor Vivid Blooms Hanging Basket,Refresh your homes exterior with the Outdoor V...,$229,Balsam Hill,Independent Website,A,Spring Artificial Flowers & Floral Dcor,https://www.balsamhill.com/f/outdoor-vivid-blo...,https://source.widen.net/content/uba1nbhgfg/we...,Image_5,flower,"[ranunculus, zinnia, dahlia, daisy, hydrangea]","[cream, green, pink, red, white, yellow]",[ivy],arrangement,planter,5,outdoor vivid bloom hanging basket,[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3474,"Mix Floral in Rectangle Vase 16""",Subscribe to our newsletters to receive 10% of...,$580.00,Winward,Independent Website,A,Luxurious Faux Flower Arrangements,https://www.winwardhome.com/products/mix-flora...,https://www.winwardhome.com/cdn/shop/files/WHD...,Image_302,flower,"[peony, rose, snapdragon]","[cream, peach, white]",[],arrangement,vase,3,mix floral in rectangle vase 16 '',[]
3476,"Caf au Lait Combo in Vase 25"" wide",Subscribe to our newsletters to receive 10% of...,$930.00,Winward,Independent Website,A,Luxurious Faux Flower Arrangements,https://www.winwardhome.com/products/cafe-au-l...,https://www.winwardhome.com/cdn/shop/files/WHD...,Image_304,flower,"[peony, rose, dahlia]","[pink, white]",[],arrangement,vase,3,caf au lait combo in vase 25 '' wide,[]
3478,"Mix Floral in Square Vase 9.5""",Subscribe to our newsletters to receive 10% of...,$800.00,Winward,Independent Website,A,Luxurious Faux Flower Arrangements,https://www.winwardhome.com/products/mix-flora...,https://www.winwardhome.com/cdn/shop/files/WHD...,Image_306,flower,"[rose, hydrangea, helleborus]","[cream, green, pink]",[],arrangement,vase,3,mix floral in square vase 9.5 '',[]
3484,"Tulip & Peony in Cylinder 9""",Subscribe to our newsletters to receive 10% of...,$500.00,Winward,Independent Website,A,Luxurious Faux Flower Arrangements,https://www.winwardhome.com/products/tulip-peo...,https://www.winwardhome.com/cdn/shop/files/SDP...,Image_312,flower,"[peony, zinnia, hydrangea]","[green, pink, yellow]",[],arrangement,vase,3,tulip & peony in cylinder 9 '',"[peony, tulip]"
3508,"Hydrangea & Snowball in Clear Vase 15"" Wide",Subscribe to our newsletters to receive 10% of...,$720.00,Winward,Independent Website,A,Luxurious Faux Flower Arrangements,https://www.winwardhome.com/products/hydrangea...,https://www.winwardhome.com/cdn/shop/products/...,Image_336,flower,"[rose, hydrangea]",[white],[],arrangement,vase,2,hydrangea & snowball in clear vase 15 '' wide,"[hydrangea, snowball]"

In [10]:
df.plant_type.value_counts()

plant_type
flower    3032
leaves     345
berry       92
            42
Name: count, dtype: int64

In [12]:
df[df.plant_type == 'leaves']['Main Img Link'].values.tolist()

['https://www.afloral.com/cdn/shop/files/AA-N1-053_df023216-f416-436b-b840-b128c0533705.jpg',
 'https://static.athome.com/images/w_1000,h_1000,c_pad,f_auto,fl_lossy,q_auto/p/124354025/string-of-pearls-in-white-oak-pot-5.jpg',
 'https://static.athome.com/images/w_1000,h_1000,c_pad,f_auto,fl_lossy,q_auto/p/124329393/eucalyptus-water-garden-in-vase-20.jpg',
 'https://static.athome.com/images/w_1000,h_1000,c_pad,f_auto,fl_lossy,q_auto/p/124232376/aloe-plant-with-cement-planter-36.jpg',
 'https://static.athome.com/images/w_1000,h_1000,c_pad,f_auto,fl_lossy,q_auto/p/124222852/greenery-arrangement-with-gold-wire-frame-6.jpg',
 'https://static.athome.com/images/w_1000,h_1000,c_pad,f_auto,fl_lossy,q_auto/p/124354019/variegated-greenery-in-metallic-pot-10.jpg',
 'https://static.athome.com/images/w_1000,h_1000,c_pad,f_auto,fl_lossy,q_auto/p/124232376/aloe-plant-with-cement-planter-36.jpg',
 'https://static.athome.com/images/w_1000,h_1000,c_pad,f_auto,fl_lossy,q_auto/p/124313872/eucalyptus-plant-with-white-planter-11.jpg',
 'https://static.athome.com/images/w_1000,h_1000,c_pad,f_auto,fl_lossy,q_auto/p/124390000/cherry-leaves-pick-12.jpg',
 'https://static.athome.com/images/w_1000,h_1000,c_pad,f_auto,fl_lossy,q_auto/p/124343030/pink-butterfly-spray-18.jpg',
 'https://static.athome.com/images/w_1000,h_1000,c_pad,f_auto,fl_lossy,q_auto/p/125000419/variegated-monstera-leaf-38.jpg',
 'https://static.athome.com/images/w_1000,h_1000,c_pad,f_auto,fl_lossy,q_auto/p/124342703/eucalyptus-stem-35.jpg',
 'https://static.athome.com/images/w_1000,h_1000,c_pad,f_auto,fl_lossy,q_auto/p/124411725/variegated-pittosporum-pick-10.jpg',
 'https://static.athome.com/images/w_1000,h_1000,c_pad,f_auto,fl_lossy,q_auto/p/124377094/grass-pick-12.jpg',
 'https://static.athome.com/images/w_1000,h_1000,c_pad,f_auto,fl_lossy,q_auto/p/125000346/ficus-spray-green-pick-14.jpg',
 'https://source.widen.net/content/kkabkknunb/webp/BLU-W_Classic-Blue-Spruce-Wreath-Set-of-2_26in-LEDCL_SSC-10.webp',
 'https://source.widen.net/content/544i5xllsy/webp/4001371_Adjustable-Metal-Wreath-Hanger_SSC-10.webp',
 'https://source.widen.net/content/hn4zmrbfga/webp/STG-1441003_Double-Wreath-Storage-Bag_SSC-40.webp',
 'https://source.widen.net/content/zecc8tyvrr/webp/CDL-2411000_Brass-Antiqued-Metal-Lantern_30in_Lifestyle-10.webp',
 'https://source.widen.net/content/uegasgec7v/webp/STG-1741001_Rolling-Multipurpose-Storage-Box_SSC.webp',
 'https://source.widen.net/content/ukbuxxtmrg/webp/URN-2211000_Gray-Sculpted-Planter_16in-Diameter_SSC.webp',
 'https://source.widen.net/content/awfpck3tik/webp/CDL-1641012_Scents-of-the-Season-Fragrance-Machine_Lifestyle-10.webp',
 'https://source.widen.net/content/bmvnuivviq/webp/CDL-2411001_8in-Outdoor-Miracle-Flame-LED-Pillar-Candle_SSC.webp',
 'https://source.widen.net/content/fwpx0myujh/webp/WRG-2341012_Cedar-Woods-Wreath_SSCR.webp',
 'https://source.widen.net/content/jukjbavlbj/webp/BFR-W_BH-Balsam-Fir-Garland_10ft-Clear_SSC-50.webp',
 'https://source.widen.net/content/ryyztor0sr/webp/FRR-W_BH-Fraser-Fir-Garland_6ft-LEDCL_SSC.webp',
 'https://source.widen.net/content/r0xjfrm7pg/webp/STG-1441003_Wreath-Storage-Bag_SSC-10.webp',
 'https://source.widen.net/content/x5qyv5dfxr/webp/URN-2211001_Taupe-Fluted-Planter-16in-Diameter_SSC.webp',
 'https://source.widen.net/content/8vnptok2sw/webp/WRG-2141021_Outdoor-Finial-Boxwood-Topiary_14in_SSC.webp',
 'https://source.widen.net/content/ffhjl5etbv/webp/BER-W_Berkshire-Mountain-Fir-Garland_10ft-Clear_SSC-50.webp',
 'https://source.widen.net/content/psingtiwwh/webp/OUT-2341015_Outdoor-Cascade-Tree-Light-String_SSC.webp',
 'https://source.widen.net/content/chgip07ct8/webp/WRG-2341012-2_Cedar-Woods-Garland_SSC.webp',
 'https://source.widen.net/content/ygxm0c5cgr/webp/WRG-2241018_Fresh-Noble-Fir-Woodland-Garland_10ft_Unlit_SSC.webp',
 'https://source.widen.net/content/jnkeqry32h/webp/VWS-W_Vermont-White-Spruce-Wreath_26in-LEDCL_SSCR.webp',
 'https://source.widen.net/content/wjg2rvwk0m/webp/BLU-W-1_10ft-Classic-Blue-Spruce-Garland_SSC.webp',
 'https://source.widen.net/content/rjma1iqxht/webp/BFR-W_BH-Balsam-Fir_26in-LEDCL_SSCR.webp',
 'https://source.widen.net/content/eciodhnd6w/webp/WRG-2441026_10ft-Fresh-Wispy-Cedar-Garland_SSC.webp',
 'https://source.widen.net/content/yhgaywkclr/webp/VWS-W_Vermont-White-Spruce-Garland_10ft-Clear_SSC.webp',
 'https://source.widen.net/content/sdh5bnpld7/webp/CDL-21410021_Outdoor-Cascading-Micro-LED-Lights_Lifestyle-10.webp',
 'https://source.widen.net/content/6nylujxeuj/webp/FRR-W_BH-Fraser-Fir-Wreath_26in-LEDCL_SSCR.webp',
 'https://source.widen.net/content/ljjyyyzyqb/webp/BER-W_22in-Double-Sided-Berkshire-Mountain-Wreath_LEDCL_SSCR.webp',
 'https://source.widen.net/content/svebj31vgs/webp/WRG-2141021_Outdoor-Double-Ball-Boxwood-Topiary_14in_SSC.webp',
 'https://source.widen.net/content/psptsvaj3e/webp/NWW-W_Norway-Spruce-Garland_10ft-LEDCL_SSC.webp',
 'https://bloomist.com/cdn/shop/files/faux-eucalyptus-wreath-desert.jpg',
 'https://bloomist.com/cdn/shop/files/artificial-asparagus-fern-desert-abigail-ahern-1200x1200.jpg',
 'https://bloomist.com/cdn/shop/files/103019_Dusty_Miller_0319-v2.jpg',
 'https://bloomist.com/cdn/shop/files/Faux-Willow-Soft-Green-1.jpg',
 'https://bloomist.com/cdn/shop/files/artificial-salix-jade-abigail-ahern_1200x1200-2.jpg',
 'https://bloomist.com/cdn/shop/files/artificial-botanical-stem-desert.jpg',
 'https://bloomist.com/cdn/shop/files/Bot_EcoFaux_EucalyptusSilverDollar_040821_DC_01_0142-v2.jpg',
 'https://bloomist.com/cdn/shop/files/ArtificialEucalyptusCreamStem-1_2a2fab04-78fa-4a32-82e0-fd6c50d699c3.jpg',
 'https://bloomist.com/cdn/shop/files/artificial-botanical-grass-stem.jpg',
 'https://bloomist.com/cdn/shop/files/artificial-foxtail-pine-stem.jpg',
 'https://bloomist.com/cdn/shop/files/artificial-frosted-pine-branch.jpg',
 'https://bloomist.com/cdn/shop/files/Faux-Queen-Annes-Lace-Purple-1.jpg',
 'https://www.dianejameshome.com/cdn/shop/files/BranchingOut.png',
 'https://www.dianejameshome.com/cdn/shop/files/BeechBranchesinGlassVase1.png',
 'https://www.dianejameshome.com/cdn/shop/files/CrowdPleaser.png',
 'https://www.dianejameshome.com/cdn/shop/files/FrillOut.png',
 'https://www.dianejameshome.com/cdn/shop/files/F25-FALLF_GLS.jpg',
 'https://www.dianejameshome.com/cdn/shop/files/F24-FALLF-GLS_Hi_Res_2400px.jpg',
 'https://www.dianejameshome.com/cdn/shop/files/AnthuriumsinCeramicVase1.png',
 'https://www.distinctivedesigns.com/pub/media/catalog/product/cache/61416bffce30193f6c0d81e86aa47813/5/0/5093a.jpg',
 'https://www.distinctivedesigns.com/pub/media/catalog/product/cache/61416bffce30193f6c0d81e86aa47813/3/3/3313b.jpg',
 'https://www.distinctivedesigns.com/pub/media/catalog/product/cache/61416bffce30193f6c0d81e86aa47813/3/3/3313c.jpg',
 'https://www.distinctivedesigns.com/pub/media/catalog/product/cache/61416bffce30193f6c0d81e86aa47813/1/9/1936_1.jpg',
 'https://www.distinctivedesigns.com/pub/media/catalog/product/cache/61416bffce30193f6c0d81e86aa47813/3/2/3240_1.jpg',
 'https://www.distinctivedesigns.com/pub/media/catalog/product/cache/61416bffce30193f6c0d81e86aa47813/8/0/8010.jpg',
 'https://www.distinctivedesigns.com/pub/media/catalog/product/cache/61416bffce30193f6c0d81e86aa47813/3/5/3500.jpg',
 'https://www.distinctivedesigns.com/pub/media/catalog/product/cache/61416bffce30193f6c0d81e86aa47813/3/3/3348.jpg',
 'https://www.distinctivedesigns.com/pub/media/catalog/product/cache/61416bffce30193f6c0d81e86aa47813/3/4/3409.jpg',
 'https://www.distinctivedesigns.com/pub/media/catalog/product/cache/61416bffce30193f6c0d81e86aa47813/1/9/1930_2.jpg',
 'https://emiliorobba.com/cdn/shop/products/049.jpg',
 'https://thefauxflowercompany.com/cdn/shop/files/artificial-flowers-luxury-lifelike-faux-artificial-silver-lambs-leaf-garland-realistic-silk-single-stems-buy-online-from-the-faux-flower-company-abx0708gr-1097160520.jpg',
 'https://thefauxflowercompany.com/cdn/shop/files/artificial-flowers-luxury-lifelike-faux-artificial-rich-green-foliage-leaves-realistic-silk-single-stems-buy-online-from-the-faux-flower-company-1176337456.jpg',
 'https://thefauxflowercompany.com/cdn/shop/products/artificial-flowers-luxury-lifelike-faux-artificial-silver-senecio-leaf-realistic-silk-single-stems-buy-online-from-the-faux-flower-company-791424252.jpg',
 'https://thefauxflowercompany.com/cdn/shop/files/artificial-flowers-luxury-lifelike-faux-artificial-green-pittosporum-leaves-realistic-silk-single-stems-buy-online-from-the-faux-flower-company-1176250256.jpg',
 'https://thefauxflowercompany.com/cdn/shop/files/artificial-flowers-luxury-lifelike-faux-artificial-green-tall-eucalyptus-realistic-silk-single-stems-buy-online-from-the-faux-flower-company-abz1129gr-6-910599451.jpg',
 'https://thefauxflowercompany.com/cdn/shop/files/artificial-flowers-luxury-lifelike-faux-artificial-yellow-ginkgo-leaves-realistic-silk-single-stems-buy-online-from-the-faux-flower-company-1079846460.jpg',
 'https://thefauxflowercompany.com/cdn/shop/files/artificial-flowers-luxury-lifelike-faux-artificial-silver-lambs-leaf-garland-realistic-silk-single-stems-buy-online-from-the-faux-flower-company-abx0708gr-1087099778.jpg',
 'https://www.flowerbx.com/media/catalog/product/cache/466bc07fdd9f3406dd5cbfa6621097e2/f/l/flowerbx-plants-product-fiddle-leaf-fig-tall-1000px_4.jpeg',
 'https://www.flowerbx.com/media/catalog/product/cache/466bc07fdd9f3406dd5cbfa6621097e2/f/l/flowerbx-plants-strelitzia-1000px-01_1.jpeg',
 'https://www.flowerbx.com/media/catalog/product/cache/466bc07fdd9f3406dd5cbfa6621097e2/p/l/plants_areca_palm_white_pot_hero_5.jpg',
 'https://media.horchow.com/f_auto,q_auto:low,ar_4:5,c_fill,dpr_2.0,w_380/01/hc_3311001_100324_m',
 'https://media.horchow.com/f_auto,q_auto:low,ar_4:5,c_fill,dpr_2.0,w_380/01/nm_3591458_100324_m',
 'https://media.horchow.com/f_auto,q_auto:low,ar_4:5,c_fill,dpr_2.0,w_380/01/nm_4437582_100327_m',
 'https://media.horchow.com/f_auto,q_auto:low,ar_4:5,c_fill,dpr_2.0,w_380/01/nm_4437587_100327_m',
 'https://media.horchow.com/f_auto,q_auto:low,ar_4:5,c_fill,dpr_2.0,w_380/01/nm_4437593_100324_m',
 'https://media.horchow.com/f_auto,q_auto:low,ar_4:5,c_fill,dpr_2.0,w_380/01/nm_4437599_100324_m',
 'https://media.horchow.com/f_auto,q_auto:low,ar_4:5,c_fill,dpr_2.0,w_380/01/nm_4437586_100324_m',
 'https://media.horchow.com/f_auto,q_auto:low,ar_4:5,c_fill,dpr_2.0,w_380/01/nm_4437590_100324_m',
 'https://www.nearlynatural.com/cdn/shop/products/artificial-18-pothos-artificial-plant-in-stone-planter-nearly-natural-233119.jpg',
 'https://www.nearlynatural.com/cdn/shop/products/artificial-16-christmas-pine-candelabrum-with-35-lights-and-pine-cones-nearly-natural-496796.jpg',
 'https://www.nearlynatural.com/cdn/shop/files/artificial-42-artificial-palm-gold-stems-set-of-3-nearly-natural-857546.jpg',
 'https://www.nearlynatural.com/cdn/shop/products/artificial-fan-palm-arrangement-nearly-natural-367910.jpg',
 'https://www.nearlynatural.com/cdn/shop/files/artificial-33-artificial-palm-frond-stems-set-of-3-stem-nearly-natural-914203.jpg',
 'https://www.nearlynatural.com/cdn/shop/products/artificial-nepthytis-artificial-plant-in-stone-planter-nearly-natural-525833.jpg',
 'https://www.nearlynatural.com/cdn/shop/files/artificial-38-artificial-palmate-fern-stems-set-of-3-stem-nearly-natural-606067.jpg',
 'https://www.nearlynatural.com/cdn/shop/files/artificial-40-artificial-eucalyptus-stems-set-of-3-stem-nearly-natural-681416.jpg',
 'https://www.nearlynatural.com/cdn/shop/products/artificial-mini-palm-artificial-plant-in-vase-set-of-3-nearly-natural-185504.jpg',
 'https://www.nearlynatural.com/cdn/shop/products/artificial-selloum-in-cylinder-glass-nearly-natural-285409.jpg',
 'https://www.nearlynatural.com/cdn/shop/products/artificial-succulent-arrangements-set-of-3-nearly-natural-626405.jpg',
 'https://newgrowthdesigns.com/cdn/shop/files/15861GR_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/1772GR_1_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/files/2411GW_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/files/2409GG_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/1755AS_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/files/2413GYW_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/DSC_5152_17997GR_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/files/2422GRW_1_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/15882GR_83b31c3d-1023-4151-944f-b74c572cdcba_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/15881GR_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/1751GR_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/15931YG_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/15931GR_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/files/2419GRB_GR21GRB_2420GRB_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/files/2451LGW_1552LG_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/15045GR_1400x.jpeg',
 'https://newgrowthdesigns.com/cdn/shop/products/15043GR_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/1712GR_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/files/1512GR2_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/files/2418GB_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/files/2406GRW_1_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/17811AS_1_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/files/17818AS_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/17823GR_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/17810_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/178231_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/15141GR.1_1400x.jpeg',
 'https://newgrowthdesigns.com/cdn/shop/products/17805MG_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/files/2417GRB_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/17806GR_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/17807GR_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/files/2404GRB_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/17809_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/17808_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/files/2408GRW_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/files/X0531GB_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/files/X0532GR_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/files/X0530YG_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/files/X0537GR_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/files/X0538GR_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/files/2417GRB_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/files/2418GB_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/9975VG_1400x.jpeg',
 'https://newgrowthdesigns.com/cdn/shop/products/X0307FR_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/E356GR_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/IFR20GR_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/IFR18GR_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/IFR28GP_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/5570_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/IFR24VE_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/X0308YG_1_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/X0308VE_1_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/X0076TTG_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/X0308GR_1_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/files/E348GR_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/files/X0524GR_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/X0371GR_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/X0332GR_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/files/E358TTG_1_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/X0417GW_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/files/X0021GRP_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/DSC_5177_X0503LG_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/E334LG_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/X0377GR_1_1_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/files/X0532GR_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/files/X0531GB_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/files/X0530YG_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/E346GR_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/X0467GR_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/X0382GR_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/E344GR_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/X0087GR_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/77003_1_1_1400x.jpeg',
 'https://newgrowthdesigns.com/cdn/shop/products/E816PS_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/X0123GR_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/IFR22GW_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/E010GY_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/IFR22GP_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/X0468GR_e61b179e-3ea2-4bc1-8193-faaddca19aa5_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/X0476GR_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/X0039GR_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/X0309GW_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/files/E001LG_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/X0514GR_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/X0518GR0_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/E008GR_2_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/X0491GR_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/files/E004GY_9a7c3bd2-7a75-4e85-93ed-74670bf9e5c7_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/E009GR_1_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/X0494_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/DSC_5333_X0497_4d189cd3-1147-49e4-bb86-0a2790046bbb_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/X0493_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/X0365GR_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/X0499RG_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/X0496GR_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/X0495GR_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/files/E300GR_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/9570YE_1400x.jpeg',
 'https://newgrowthdesigns.com/cdn/shop/products/IFR26RG_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/X0353GR_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/X0520GR_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/E350GR_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/X0519GR_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/X0515TTG_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/E352GR_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/E816GR_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/X0467GY_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/X0488GR_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/X0385SG_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/X0523TTG_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/X0385GR_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/14524C_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/E354GR_BACK_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/X0328GR_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/X0326GR_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/products/X0327GR_1400x.jpg',
 'https://newgrowthdesigns.com/cdn/shop/files/E864YG_E862GR_E860RG_1400x.jpg',

#### quick view

In [8]:
flowers = df[df.plant_type == 'flower']
flowers = df[df.how_many_flowers > 0]
arrangements = flowers[flowers.product_type == 'arrangement']
single_stems = flowers[flowers.product_type == 'single stem']

pd.DataFrame(flowers.product_type.value_counts(normalize = True)).round(2)

              proportion
product_type
arrangement         0.68
single stem         0.29
wreath              0.02
other               0.01
garland             0.00
flowerhead          0.00
teardrop            0.00

#### One flower vs. multiple flowers

In [9]:
pd.DataFrame(flowers.how_many_flowers.value_counts(normalize = True)).round(2)

                  proportion
how_many_flowers
1                       0.83
2                       0.09
3                       0.06
4                       0.03
5                       0.00
6                       0.00
7                       0.00

### DF collection

- Keyword usage needs to be consistent and professional. Best achieved if we provide a standard list of possible choices. Otherwise, it will be all over the place. For instance, GPT might call 1 style 2 different words...Definition of each word needs to be very clear.
- Need to make sure keywords aren't being used randomly...(might want to remove text generation...). Maybe use text generation ONLY for the material. 
-

In [10]:
def filter_rows_by_keywords(df, col, searchwords):
    if not isinstance(searchwords, (list, tuple)):
        raise ValueError("searchwords must be a list or tuple of strings.")

    mask = df[col].apply(lambda lst: all(word in lst for word in searchwords))
    return df[mask]

In [11]:
# rustic = filter_rows_by_keywords(df, "style", ['rustic'])

#### Flower type

In [17]:
counts, pcts, color_table = df_to_colortable(df, "flower_type")
color_table

store_sizes [327, 18, 115, 53, 218, 351, 185, 79, 189, 116, 249, 616, 88, 166, 118, 141, 52, 90, 340]
Index(['Aflora', 'At Home', 'Balsam Hill', 'Bloomist', 'Diane James Home',
       'Distinctive Designs', 'Emilio Robba', 'Faux Flower Company',
       'Flowerbx', 'Horchow', 'Nearly Natural', 'New Growth Designs',
       'Perigold', 'Pottery Barn', 'Prestige Botanicals', 'Real Touch Flowers',
       'Serene Spaces', 'Stilla', 'Winward'],
      dtype='object', name='store_name')

In [18]:
counts.index.values.tolist()

['hydrangea',
 'rose',
 'orchid',
 'peony',
 'ranunculus',
 'tulip',
 'dahlia',
 'magnolia',
 'calla lily',
 'cherryblossom',
 'lily',
 'anemone',
 'daisy',
 'delphinium',
 'amaryllis',
 'lilac',
 'chrysanthemum',
 'carnation',
 'hellebore',
 'poppy',
 'protea',
 'anthurium',
 'allium',
 'poinsettia',
 'sunflower',
 'zinnia',
 'lavender',
 'gladiolus',
 'viburnum',
 'snapdragon',
 'hyacinth',
 'jasmine',
 'geranium',
 'narcissus',
 'iris',
 'bougainvillea',
 'pansy',
 'sweet pea',
 'bird of paradise',
 'gardenia',
 'lily of the valley',
 "baby's breath",
 'lisianthus',
 'camellia',
 'dogwood',
 'petunia',
 'bromeliad',
 'heliconia',
 'waxflower',
 'freesia',
 'grape hyacinth',
 'pincushion protea',
 'forsythia',
 'cosmos',
 'bells of ireland',
 'hibiscus',
 'amaranthus',
 'yarrow',
 'succulent',
 'helleborus',
 'mimosa',
 'astilbe',
 'flower',
 'primrose',
 'tuberose',
 'agapanthus',
 'cornflower',
 'gerbera',
 'stock',
 'wisteria',
 'artichoke',
 'azalea',
 'scabiosa',
 'african violet',
 "queen anne's lace",
 'roses',
 'gloriosa lily',
 'kalanchoe',
 'cyclamen',
 'marigold',
 'pussy willow',
 'salvia',
 'thistle',
 'violet',
 'water lily',
 'billy balls',
 'cockscomb',
 'craspedia',
 'foxglove',
 'kangaroo paw',
 'ornamental cabbage',
 'unknown',
 'aloe',
 'alstroemeria',
 'artichoke flower',
 'banksia',
 'begonia',
 'bell of ireland',
 'bellflower',
 'billy buttons',
 'blossom',
 'california poppy',
 'campanula',
 'clematis',
 'crocus',
 'dianthus',
 'eucalyptus',
 'forget me not',
 'fountain grass',
 'fritillaria',
 'gerbera daisy',
 'ginger',
 'gypsophila',
 'millet',
 'other',
 'peace lily',
 'phlox',
 'plumeria',
 'pompom flower',
 'statice',
 'strawberry flower',
 'veronica',
 'wildflower']

In [13]:
counts, pcts, color_table = df_to_colortable(df, "flowers_in_name")
color_table

store_sizes [327, 18, 115, 53, 218, 351, 185, 79, 189, 116, 249, 616, 88, 166, 118, 141, 52, 90, 340]
Index(['Aflora', 'At Home', 'Balsam Hill', 'Bloomist', 'Diane James Home',
       'Distinctive Designs', 'Emilio Robba', 'Faux Flower Company',
       'Flowerbx', 'Horchow', 'Nearly Natural', 'New Growth Designs',
       'Perigold', 'Pottery Barn', 'Prestige Botanicals', 'Real Touch Flowers',
       'Serene Spaces', 'Stilla', 'Winward'],
      dtype='object', name='store_name')

#### Flower combinations

1. Filter all rows where there's more than 1 flower
2. Look at the flowers!

In [76]:
multiple_flowers = flowers[flowers.how_many_flowers > 1]

In [77]:
counts, pcts, color_table = df_to_colortable(multiple_flowers, "flower_type", join_keywords = True)
color_table

store_sizes [2, 49, 86, 99, 10, 10, 4, 32, 34, 29, 10, 22, 1, 67, 60]
Index(['Aflora', 'Balsam Hill', 'Diane James Home', 'Distinctive Designs',
       'Emilio Robba', 'Faux Flower Company', 'Flowerbx', 'Horchow',
       'Nearly Natural', 'New Growth Designs', 'Perigold', 'Pottery Barn',
       'Serene Spaces', 'Stilla', 'Winward'],
      dtype='object', name='store_name')

#### Container

In [38]:
container_counts = pd.DataFrame(arrangements.container.value_counts(normalize = True).round(2))
container_counts

           proportion
container
vase             0.70
pot              0.21
planter          0.07
none             0.01
basket           0.01
other            0.00

#### Product type 

Single stem vs arrangement

In [21]:
counts, pcts, color_table = df_to_colortable(df, "product_type")
color_table

store_sizes [327, 18, 115, 53, 218, 351, 185, 79, 189, 116, 249, 616, 166, 118, 141, 52, 90]
Index(['Aflora', 'At Home', 'Balsam Hill', 'Bloomist', 'Diane James Home',
       'Distinctive Designs', 'Emilio Robba', 'Faux Flower Company',
       'Flowerbx', 'Horchow', 'Nearly Natural', 'New Growth Designs',
       'Pottery Barn', 'Prestige Botanicals', 'Real Touch Flowers',
       'Serene Spaces', 'Stilla'],
      dtype='object', name='store_name')

In [22]:
product_type_distribution = pd.DataFrame(df.product_type.value_counts(normalize = True).round(2))
product_type_distribution

              proportion
product_type
arrangement         0.64
single stem         0.29
wreath              0.03
other               0.02
garland             0.01
                    0.00
flowerhead          0.00
teardrop            0.00

#### Colors

In [25]:
counts, pcts, color_table = df_to_colortable(df, "flower_colors")
color_table

store_sizes [327, 18, 115, 53, 218, 351, 185, 79, 189, 116, 249, 616, 88, 166, 118, 141, 52, 90, 340]
Index(['Aflora', 'At Home', 'Balsam Hill', 'Bloomist', 'Diane James Home',
       'Distinctive Designs', 'Emilio Robba', 'Faux Flower Company',
       'Flowerbx', 'Horchow', 'Nearly Natural', 'New Growth Designs',
       'Perigold', 'Pottery Barn', 'Prestige Botanicals', 'Real Touch Flowers',
       'Serene Spaces', 'Stilla', 'Winward'],
      dtype='object', name='store_name')

In [26]:
# counts, pcts, color_table = df_to_colortable(df, "flower_colors", join_keywords = True)
# color_table

In [27]:
counts.index.values.tolist()

['white',
 'pink',
 'yellow',
 'red',
 'green',
 'purple',
 'orange',
 'cream',
 'blue',
 'peach',
 'light green',
 'light blue',
 'light pink',
 'magenta',
 'brown',
 'light purple',
 'coral',
 'dark red',
 'tan',
 'pale pink',
 'beige',
 'dark pink',
 'pale yellow',
 'gold',
 'bright pink',
 'burgundy',
 'dark purple',
 'grey',
 'lavender',
 'violet']

#### Flower combination

In [51]:
def filter_rows_by_all_keywords(df, col, keywords, all_keywords = False):
    if not keywords or len(keywords) == 0:
        return df
    
    def contains_all_keywords(cell):
        # Handle NaN or None
        if cell is None:
            return False

        # Handle numpy arrays, lists, tuples, sets uniformly
        if isinstance(cell, (np.ndarray, list, tuple, set)):
            cell_iterable = cell
        else:
            # Try to detect NaN scalars
            if pd.isna(cell):
                return False
            cell_iterable = [cell]

        # Lowercase all items for case-insensitive comparison
        cell_strs = [str(item).lower() for item in cell_iterable]

        # Check if every keyword appears in any of the cell strings
        if all_keywords:
            return all(
                any(keyword.lower() in s for s in cell_strs)
                for keyword in keywords
            )
        else:
            return any(
                any(keyword.lower() in s for s in cell_strs)
                for keyword in keywords
            )

    mask = df[col].apply(contains_all_keywords)
    return df[mask]

In [54]:
hydrangea = filter_rows_by_all_keywords(flowers, 'flower_type', ['hydrangea'])

In [55]:
counts, pcts, color_table = df_to_colortable(hydrangea, "flower_type")
color_table

store_sizes [58, 26, 8, 58, 99, 9, 18, 1, 34, 54, 74, 13, 31, 16, 29, 1, 46, 62]
Index(['Aflora', 'Balsam Hill', 'Bloomist', 'Diane James Home',
       'Distinctive Designs', 'Emilio Robba', 'Faux Flower Company',
       'Flowerbx', 'Horchow', 'Nearly Natural', 'New Growth Designs',
       'Perigold', 'Pottery Barn', 'Prestige Botanicals', 'Real Touch Flowers',
       'Serene Spaces', 'Stilla', 'Winward'],
      dtype='object', name='store_name')